### ISSUE TITLE
Pew pew pews are not accessible without internet

### ISSUE THREAD

**Issue by tomakado** [rustamgarifulin/rustamgarifulin#2]
Hello! Thank you for your project. it's really nice and handy. But I have one problem with it: if I pew pew pew with internet all right. But when I'm trying to pew pew pew locally without network connection it seems not working. Is this tool depend on internet connection? It would be nice to pew pew pew in village or bunker.

Thanks!

**Comment by rustamgarifulin** [comment]
Pew! Pew pew pew, pew pew pew!

Pew!

**Comment by rustamgarifulin** [comment]
@tomakado, pew pew! #1 

- [x] pew;
- [x] peeeew;
- [ ] pew!

**Comment by tomakado** [comment]
Thank you! Pew pew pew!
